version: "4.6"

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pharmacy_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_DB=pharmacy_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
